name: Publish Package

on:
  push:
    branches:
      - "**"
    tags:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      # If current run is from a branch pack without versioning and don't publish
      - name: Pack On Branch
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: |
          dotnet pack -c Release -o output
      # If current run is from a tag pack with tag name as version and publish
      - name: Get Tag Name
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Pack On Tag
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        env:
          TAG_NAME: ${{ env.TAG_NAME }}
        run: |
          dotnet pack -c Release -o output /p:Version=${TAG_NAME} /p:AssemblyVersion=${TAG_NAME} \
            /p:FileVersion=${TAG_NAME} /p:InformationalVersion=${TAG_NAME}

