name: Publish Package

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      # If current run is from a branch pack without versioning and don't publish
      - name: Pack On Branch
        if: !${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          dotnet pack -c Release -o output
      # If current run is from a tag pack with tag as version and publish
      - name: Pack On Tag
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          dotnet pack -c Release -o output /p:Version=1.0.0 /p:AssemblyVersion=1.0.0.0 /p:FileVersion=1.0.0.0 \
            /p:InformationalVersion=1.0.0  

